version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp-image:latest
    ports:
      - "8000:8000"
    networks:
      - my_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
